name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-09"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjE2NmJhMDAtNDlkOC00OWNmLWEyZTAtYjIzMzgyNWY3MTEyIiwidGVuYW50X2lkIjoiY2NiMDQzMGYxYTM4ZGEwY2UyNjRjZDcwMTRiZDk0ODI1OWYyZGMwYmVlNmIzYWZjZWFhMDA1MWQ4MThjZjFmNyIsImludGVybmFsX3NlY3JldCI6Ijc5NDNlOGQzLTU0MjAtNDZjMi05ZGRjLTg4OGU5ZDdmNGFkMSJ9.arnJwXhfDIa-vxWM4gnGP2oYcfNPcD-aoCz3vnclRFM"
JWT_KEY="hxghsvx"


