name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-09"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODUxZjUxNzEtZTFmMy00YzE0LWFkNTEtNmI5N2M5ZDE1YTQ2IiwidGVuYW50X2lkIjoiY2NiMDQzMGYxYTM4ZGEwY2UyNjRjZDcwMTRiZDk0ODI1OWYyZGMwYmVlNmIzYWZjZWFhMDA1MWQ4MThjZjFmNyIsImludGVybmFsX3NlY3JldCI6Ijc5NDNlOGQzLTU0MjAtNDZjMi05ZGRjLTg4OGU5ZDdmNGFkMSJ9.UNpAQ810j8rHSgyEWW3OYh5ETXHg0DH4D8-MBnTDe74"
JWT_KEY="hxghsvx"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1